#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Portfolio',     url: 'portfolio'}
- {name: 'Contact',  url: 'contact'}
- {name: 'Shop', url: 'http://lauradzeng.square.site/'}

#-------------------------------
# Projects Section

projects:
- {name: 'Chili B POV Intro/Outro Animations',   url: 'chilibanimation'}
- {name: 'Common Area Writers Membership Stickers',   url: 'camsticker'}
- {name: 'Neighborhood Cat-Alog', url: 'neighborhoodcatalog'}
- {name: 'lauradzeng Stickers',  url: 'personal'}

#-------------------------------
# Contact Section

social:
- {icon: 'envelope', link: 'mailto:lauradzeng@gmail.com'}
- {icon: 'instagram', link: 'https://instagram.com/lauradzeng'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Laura Zeng's personal portfolio "
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
